server:
  port: 28888
spring:
  datasource:
    username: root
    password: 111111
    url: 'jdbc:mysql://127.0.0.1:3306/vin?useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=Asia/Hong_Kong&useSSL=false'
    druid:
      #最大活跃数
      maxActive: 5
      #初始化数量
      initialSize: 2
      #最大连接等待超时时间
      maxWait: 60000
      #打开PSCache，并且指定每个连接PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 200
      #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
mybatis:
  mapper-locations: 'classpath*:mapper/**/*Mapper.xml'
  configuration:
    map-underscore-to-camel-case: true
